const cats=[
['🌱','Lawn Care','Build a thicker, greener lawn with practical mowing, watering, aeration and overseeding guides.','/lawn-care','lawn'],
['🔍','Lawn Diseases','Identify brown patch, dollar spot, rust, snow mold and other common turf problems.','/lawn-diseases','disease'],
['🐞','Garden Pests','Spot and manage grubs, aphids, Japanese beetles and other common garden pests.','/garden-pests','pests'],
['🍃','Plant Diseases','Diagnose powdery mildew, black spot and other common plant diseases.','/plant-diseases','plants'],
['🍂','Seasonal Care','Month-by-month yard tasks for changing weather across the USA and Canada.','/seasonal-care','season'],
['❄️','Winterization','Protect irrigation, trees, lawns and containers before freezing weather arrives.','/winterization','winter']
];
const featured=[
['Brown Spots on Lawn in Summer','Learn the common causes of summer brown patches and what to check before treating.','Lawn diagnosis'],
['Why Grass Turns Yellow After Rain','Separate temporary water stress from drainage, nutrient and disease problems.','Lawn care'],
['White Mold on Garden Soil','See what the white growth may be and when your plants actually need intervention.','Plant health']
];
export default function Home(){return <><section className="hero"><div className="heroCopy"><div className="eyebrow light">USA & CANADA YARD CARE</div><h1>Fix Your Yard.<br/><span>Grow With Confidence.</span></h1><p>Clear, practical solutions for lawn problems, garden pests, plant diseases and seasonal maintenance—without the guesswork.</p><div className="heroActions"><a className="btn" href="/lawn-diseases">Diagnose a Lawn Problem →</a><a className="ghostBtn" href="/seasonal-care">Explore Seasonal Care</a></div><div className="trust"><span>✓ Practical fixes</span><span>✓ Seasonal guidance</span><span>✓ USA + Canada</span></div></div><div className="yardScene" aria-label="Illustrated healthy backyard"><div className="sun">☀️</div><div className="tree">🌳</div><div className="home">🏡</div><div className="flowers">🌷🌼🌷</div><div className="grass">🌱 🌿 🌱 🌿 🌱</div></div></section><main><section className="wrap problemSection"><div className="sectionHead"><div><div className="eyebrow">YARD PROBLEM SOLVER</div><h2>What does your yard need today?</h2></div><p>Choose a topic and get straight to practical diagnosis, treatment and prevention guides.</p></div><div className="grid">{cats.map(c=><a className={'card '+c[4]} href={c[3]} key={c[1]}><div className="iconBubble">{c[0]}</div><h3>{c[1]}</h3><p>{c[2]}</p><b>Explore guides →</b></a>)}</div></section><section className="diagnoseBand"><div><div className="eyebrow light">QUICK DIAGNOSIS</div><h2>Start with what you can see.</h2><p>Brown spots, yellow grass, white growth, thinning turf or unusual insects? Match the symptom first, then narrow down the likely cause before choosing a treatment.</p><a className="whiteBtn" href="/lawn-diseases">Find the likely cause →</a></div><div className="symptoms"><span>🟤 Brown patches</span><span>🟡 Yellow grass</span><span>⚪ White growth</span><span>🐛 Lawn insects</span></div></section><section className="wrap"><div className="sectionHead"><div><div className="eyebrow">POPULAR PROBLEMS</div><h2>Helpful guides for common yard issues</h2></div><p>Focused answers designed to help homeowners understand the problem before taking action.</p></div><div className="featuredGrid">{featured.map((x,i)=><article className={'feature f'+i} key={x[0]}><div className="photoMock"><span>{i===0?'☀️🌱🟤':i===1?'🌧️🌱🟡':'🪴🌿⚪'}</span></div><div className="featureBody"><small>{x[2]}</small><h3>{x[0]}</h3><p>{x[1]}</p><span className="read">Guide coming next →</span></div></article>)}</div></section><section className="seasonBlock"><div className="seasonArt">🍁 <span>🏡</span> ❄️</div><div><div className="eyebrow">SEASONAL YARD CARE</div><h2>Prepare your yard before the weather changes.</h2><p>From spring soil preparation to fall cleanup and winter protection, plan the right jobs at the right time for your climate.</p><a className="darkBtn" href="/winterization">See winterization guides →</a></div></section></main></>}