const pages={
"lawn-care":{title:"Lawn Care",desc:"Mowing, watering, fertilizing, seeding and practical lawn maintenance.",article:["Fall Lawn Care Checklist 2026: Seed, Aerate and Feed at the Right Time","/lawn-care/fall-lawn-care-checklist-2026","https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=1200&q=82"]},
"lawn-diseases":{title:"Lawn Diseases",desc:"Identify common turf diseases and learn practical ways to help your lawn recover.",article:["Lawn Rust in Fall: How to Identify Orange Grass and Fix It","/lawn-diseases/how-to-identify-lawn-rust-in-fall","https://myelitelawncare.com/media/images/imported/2022/08/elite-lawn-care-common-lawn-disease-07.jpg?width=1920"]},
"garden-pests":{title:"Garden Pests",desc:"Identify garden pests and protect plants with practical prevention strategies.",article:["Fall Garden Pests 2026: Yellowjackets, Boxelder Bugs and What to Do","/garden-pests/fall-garden-pests-yellowjackets-boxelder-bugs","https://botanix.com/cdn/shop/articles/Scarabee_Japonais_e78286a5-a2d5-4abf-b5c3-4edd171f7ff4.jpg?v=1783956229"]},
"plant-diseases":{title:"Plant Diseases",desc:"Diagnose common plant diseases and learn prevention and treatment basics.",article:["Powdery Mildew on Plants: How to Identify, Treat and Prevent It","/plant-diseases/how-to-treat-powdery-mildew-on-plants","https://upload.wikimedia.org/wikipedia/commons/9/9e/Powdery_mildew_on_leaf.jpg"]},
"seasonal-care":{title:"Seasonal Care",desc:"Timely yard and garden tasks for spring, summer, fall and winter.",article:["Fall Yard Cleanup Checklist 2026: What to Do Before Winter","/seasonal-care/fall-yard-cleanup-checklist-2026","https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1200&q=82"]},
"winterization":{title:"Winterization",desc:"Prepare lawns, gardens and outdoor plants for freezing weather.",article:["How to Protect Outdoor Potted Plants From Frost and Winter Cold","/winterization/how-to-protect-outdoor-potted-plants-from-frost","https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=1200&q=82"]},
"about":{title:"About YardFixGuide",desc:"Practical lawn and garden problem-solving guides for homeowners across the U.S. and Canada."},
"contact":{title:"Contact",desc:"Contact YardFixGuide about our lawn and garden guides."}};
export async function generateMetadata({params}){const p=await params,d=pages[p.slug];return d?{title:d.title+" | YardFixGuide",description:d.desc}:{}}
export default async function Page({params}){const p=await params,d=pages[p.slug];if(!d)return <main className="article"><h1>Page not found</h1></main>;return <main className="article categoryPage"><div className="eyebrow">YARDFIXGUIDE</div><h1>{d.title}</h1><p className="articleLead">{d.desc}</p>{d.article&&<a className="categoryArticle categoryArticleVisual" href={d.article[1]}><img src={d.article[2]} alt={d.article[0]}/><div><span>NEW GUIDE • SEPTEMBER 2026</span><h2>{d.article[0]}</h2><p>Practical step-by-step guidance, identification tips, prevention advice and answers to common questions.</p><b>Read the guide →</b></div></a>}</main>}
